services:
    # azure driver connector
    sfynx_api_media.azure_blob_proxy_factory:
        class: 'Gaufrette\Adapter\AzureBlobStorage\BlobProxyFactory'
        arguments: ['%sfynx.apimedia.blob_storage.connection_string%']
