parameters:
    doc_api_controller_get_one.class: Sfynx\ApiMediaBundle\Layers\Presentation\Coordination\Media\Query\GetOneController
    doc_api_controller_get_one_binary.class: Sfynx\ApiMediaBundle\Layers\Presentation\Coordination\Media\Query\GetOneBinaryController
    doc_api_controller_get_endpoint.class: Sfynx\ApiMediaBundle\Layers\Presentation\Coordination\Media\Query\GetEndpointController

services:
    #
    # QUERY SERVICES
    #
    doc_api_controller_get_one:
        class: '%doc_api_controller_get_one.class%'
        public: true
        arguments:
            - '@sfynx.apimedia.manager.media.entity'
            - '%sfynx_api_media.cache_storage_provider%'

    doc_api_controller_get_one_binary:
        class: '%doc_api_controller_get_one_binary.class%'
        public: true
        arguments:
            - '@sfynx.apimedia.manager.media.entity'

    doc_api_controller_get_endpoint:
        class: '%doc_api_controller_get_endpoint.class%'
        public: true
        arguments:
            - '@sfynx.apimedia.manager.media.entity'