parameters:
    doc_api_controller_create_jwt_token.class: Sfynx\ApiMediaBundle\Layers\Presentation\Coordination\Media\Command\CreateJwtTokenController
    doc_api_controller_create_one.class: Sfynx\ApiMediaBundle\Layers\Presentation\Coordination\Media\Command\CreateOneController
    doc_api_controller_update_one.class: Sfynx\ApiMediaBundle\Layers\Presentation\Coordination\Media\Command\UpdateOneController
    doc_api_controller_delete_one.class: Sfynx\ApiMediaBundle\Layers\Presentation\Coordination\Media\Command\DeleteOneController

services:
    #
    # COMMAND SERVICES
    #
    doc_api_controller_create_jwt_token:
        class: '%doc_api_controller_create_jwt_token.class%'
        public: true
        arguments:
            - '@sfynx_api_media.securing.signed.urls'

    doc_api_controller_create_one:
        class: '%doc_api_controller_create_one.class%'
        public: true
        arguments:
            - '@sfynx.apimedia.manager.media.entity'
            - '%sfynx.apimedia.quality%'

    doc_api_controller_update_one:
        class: '%doc_api_controller_update_one.class%'
        public: true
        arguments:
            - '@sfynx.apimedia.manager.media.entity'

    doc_api_controller_delete_one:
        class: '%doc_api_controller_delete_one.class%'
        public: true
        arguments:
            - '@sfynx.apimedia.manager.media.entity'
